In [33]:
import pandas as pd
import numpy as np
import sklearn 
from sklearn.naive_bayes import GaussianNB 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix , accuracy_score , f1_score , recall_score
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
df = pd.read_csv('/kaggle/input/adult-data/adult.data')

In [35]:
df.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   39              32560 non-null  int64
 1    State-gov      32560 non-null  object
 2    77516          32560 non-null  int64
 3    Bachelors      32560 non-null  object
 4    13             32560 non-null  int64
 5    Never-married  32560 non-null  object
 6    Adm-clerical   32560 non-null  object
 7    Not-in-family  32560 non-null  object
 8    White          32560 non-null  object
 9    Male           32560 non-null  object
 10   2174           32560 non-null  int64
 11   0              32560 non-null  int64
 12   40             32560 non-null  int64
 13   United-States  32560 non-null  object
 14   <=50K          32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [37]:
df.isnull().sum()

39                0
 State-gov        0
 77516            0
 Bachelors        0
 13               0
 Never-married    0
 Adm-clerical     0
 Not-in-family    0
 White            0
 Male             0
 2174             0
 0                0
 40               0
 United-States    0
 <=50K            0
dtype: int64

In [38]:
df.drop_duplicates()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [39]:
encoder = OneHotEncoder()

In [40]:
x = df.iloc[: , :-1]
y = df[df.columns[-1]]

In [41]:
x.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States

In [42]:
y.head()

0     <=50K
1     <=50K
2     <=50K
3     <=50K
4     <=50K
Name:  <=50K, dtype: object

In [43]:
x = np.asarray(x)
y = np.asarray(y)

In [44]:
y = y.reshape(-1 , 1)

In [45]:
x = encoder.fit_transform(x)
y = encoder.fit_transform(y)

In [46]:
x = x.toarray()
y = y.toarray()

In [47]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 42)

In [48]:
model = GaussianNB()

In [49]:
y_t = []
for i in range(len(y_train)):
        y_t.append(y_train[i][0])

In [50]:
y_s = []
for i in range(len(y_test)):
    y_s.append(y_test[i][0])

In [51]:
y_t = np.array(y_t)

In [52]:
print(x_train.shape[0] , y_train.shape[0])

26048 26048

In [53]:
print(x_train.shape[0] , y_t.shape[0])

26048 26048

In [54]:
model.fit(x_train , y_t)

GaussianNB()

In [55]:
pred = model.predict(x_test)

In [56]:
cm = confusion_matrix(y_s , pred)

In [57]:
TN = cm[0 , 0]
FP = cm[0 , 1]
FN = cm[1 , 0]
TP = cm[1 , 1]

# Accuracy:

In [58]:
accuracy_score(pred , y_s)

0.4946253071253071

# Sensitivity:

In [59]:
recall_score(y_s , pred)

0.38375407166123776

# Specificity:

In [60]:
print(TN / (TN + FP))

0.835

# Posterior probability of making over 50k a year:

In [61]:
print(TP /(TP + FP))

0.8771521637971149